[package]
name = "base64-ng-perf"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[features]
default = ["simd"]
simd = ["base64-ng/simd"]

[dependencies]
base64 = "=0.23.0"
base64ct = "=1.8.3"
base64-ng = { path = "..", version = "2.0.1", default-features = false, features = ["alloc", "std", "stream"] }
